#!/usr/bin/python2.7 -tt

from socket import *
import sys

fail_response = """HTTP/1.1 404 Not Found\r\nContent-type: text/html\r\nContent-length: 113
\r\n\r\n<html><head><title>Not Found</title></head><body>\r\nSorry, the object you requested was not found.\r\n</body></html>\r\n\r\n"""

response = "HTTP/1.0 200 OK\r\nContent-Type: text/html\r\nContent-Length: "


if __name__ == "__main__":
    s = socket()
    try:
        port = int(sys.argv[1])
    except ValueError:
        print("Invalid port argument: " + sys.argv[1])
        sys.exit(-1)

    s.connect(("localhost", port))
    endpoint_counter = 1
    request = ""
    while 1:
        req = s.recv(1024)
        request += req
        if request.count('\r\n\r\n') == 0:
            continue
        if request.count('\r\n\r\n') == 1:
            lines = request.split('\r\n')
            if lines[0].find('GET /counter ') == -1:
                s.send(fail_response)       # Requested end point is not a GET /counter
            else:
                res = response + str(len(str(endpoint_counter))) + "\r\n\r\n" + str(endpoint_counter) + "\r\n\r\n"
                s.send(res)
                endpoint_counter += 1
        request = ""


